server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_games_db
    username: ${LOCAL_DATABASE_USERNAME}
    password: ${LOCAL_DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      data-locations: classpath*:db/data/game.sql
      encoding: UTF-8
      mode: embedded
  messages:
    basename: errors
    encoding: UTF-8

logging:
  level:
    test.splab.springgames.modules : debug

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

slack:
  message:
    webhook:
      url: ${SLACK_WEBHOOK_URL}

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      data-locations: classpath*:db/data/game.sql
      encoding: UTF-8
      mode: never

logging:
  level:
    com.book.app.modules: debug
